# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 241)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setStyleSheet("* {\n"
"    font-family: \"Nirmala UI\";\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: rgb(22, 22, 22);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size: 16px;\n"
"    border: 1px solid #888;\n"
"    border-radius: 7px;\n"
"    padding: 5px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: #fff;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: orange;\n"
"    color: orange;\n"
"}\n"
"\n"
"#resultado {\n"
"    border: none;\n"
"    border-bottom: 1px solid #888;\n"
"    border-radius: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-size: 20px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(249, 158, 0);\n"
"    color: white;\n"
"    padding-bottom: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(231, 146, 0);\n"
"    color:rgba(255, 255, 255, .8);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-bottom: 8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.num1.setObjectName("num1")
        self.verticalLayout.addWidget(self.num1)
        self.num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.num2.setObjectName("num2")
        self.verticalLayout.addWidget(self.num2)
        self.resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.resultado.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resultado.setObjectName("resultado")
        self.verticalLayout.addWidget(self.resultado)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 3, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_sumar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sumar.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_sumar.setMaximumSize(QtCore.QSize(45, 45))
        self.btn_sumar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sumar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_sumar.setObjectName("btn_sumar")
        self.gridLayout.addWidget(self.btn_sumar, 0, 0, 1, 1)
        self.btn_restar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_restar.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_restar.setMaximumSize(QtCore.QSize(45, 45))
        self.btn_restar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_restar.setObjectName("btn_restar")
        self.gridLayout.addWidget(self.btn_restar, 0, 1, 1, 1)
        self.btn_multiplicar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiplicar.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_multiplicar.setMaximumSize(QtCore.QSize(45, 45))
        self.btn_multiplicar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_multiplicar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_multiplicar.setObjectName("btn_multiplicar")
        self.gridLayout.addWidget(self.btn_multiplicar, 1, 0, 1, 1)
        self.btn_dividir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dividir.setMinimumSize(QtCore.QSize(45, 45))
        self.btn_dividir.setMaximumSize(QtCore.QSize(45, 45))
        self.btn_dividir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dividir.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_dividir.setObjectName("btn_dividir")
        self.gridLayout.addWidget(self.btn_dividir, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 1, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora simple con PyQt5"))
        self.num1.setPlaceholderText(_translate("MainWindow", "Número 1"))
        self.num2.setPlaceholderText(_translate("MainWindow", "Número 2"))
        self.resultado.setPlaceholderText(_translate("MainWindow", "Resultado..."))
        self.btn_sumar.setText(_translate("MainWindow", "+"))
        self.btn_restar.setText(_translate("MainWindow", "-"))
        self.btn_multiplicar.setText(_translate("MainWindow", "x"))
        self.btn_dividir.setText(_translate("MainWindow", "÷"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
